# Generated by Django 3.2.5 on 2024-06-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='mygym', primary_key=True, serialize=False)),
                ('author', models.CharField(default='admin', max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
